sudo: required
dist: bionic
language: java
jdk: openjdk8
jobs:
  include:
    #Other modules can refer to oap-cache-oap to build independent travis-ci job,
    #oap-cache-oap is a CI building demo of the corresponding module oap-cache/oap.
    - name: sql-ds-cache
      before_install:
      - sudo apt-get install libpthread-stubs0-dev
      - sudo apt-get install libnuma-dev
      - sudo apt-get install cmake
      - sudo apt-get install asciidoctor libkmod-dev libudev-dev uuid uuid-dev libjson-c-dev systemd libkeyutils-dev
      - sudo apt-get install pandoc libgtest-dev pkg-config libtbb-dev rapidjson-dev valgrind
      install:
      - # Download spark 3.0.0
      - "[ -f spark ] || mkdir spark && cd spark && wget https://archive.apache.org/dist/spark/spark-3.0.0/spark-3.0.0-bin-hadoop2.7.tgz && cd .."
      - "tar -xf ./spark/spark-3.0.0-bin-hadoop2.7.tgz"
      - "export SPARK_HOME=`pwd`/spark-3.0.0-bin-hadoop2.7"
      before_script:
      - git clone https://github.com/oap-project/oap-tools.git
      - cd oap-tools/dev
      - ./install_vmemcache.sh
      - ./install_memkind.sh
      - ./install_pmdk.sh
      - ./install_pmemkv.sh
      - git clone https://github.com/oap-project/pmem-common.git
      - ./pmem-common/src/native/memkind/compile.sh
      - ./pmem-common/src/native/libpmemblk/compile.sh
      - sudo cp ./oap-common/src/resources/linux/64/lib/libpmplatform.so /usr/lib/
      - sudo cp ./oap-common/src/resources/linux/64/lib/libpmblkplatform.so /usr/lib/
      - sudo ldconfig /usr/lib
      - cd pmem-common
      - mvn install -Ppersistent-memory -Pvmemcache -Plibpmemblk
      script:
      - cd ${TRAVIS_BUILD_DIR}
      - mvn clean test -q
