site_name: SQL DS Cache

nav:
- Overview: Architecture-Overview.md
- User Guide: User-Guide.md
- OAP Installation Guide: OAP-Installation-Guide.md
- Advanced Configuration: Advanced-Configuration.md
- Developer Guide: Developer-Guide.md
- Version Selector: "../"


repo_name: "Fork on Github"
repo_url: "https://github.com/HongW2019/sql-ds-cache-website.git"
edit_uri: ""

theme: readthedocs

plugins:
  - search
  - mkdocs-versioning:
      version: 1.0.0
      exclude_from_nav: ["image", "js", "css", "fonts", "img"]
